# Rede pequena - 8 nós
num_nodes: 8
min_neighbors: 2
max_neighbors: 3

resources:
  n1: "r1, r2"
  n2: "r3"
  n3: "r4, r5"
  n4: "r6"
  n5: "r7, r8"
  n6: "r9"
  n7: "r10, r11"
  n8: "r12"

edges:
  - "n1, n2"
  - "n1, n3"
  - "n2, n4"
  - "n2, n5"
  - "n3, n6"
  - "n4, n7"
  - "n5, n8"
  - "n6, n7"
  - "n7, n8"